class ExtractedContent:

    contents = {
        '001-012l_S3_Analgesie-Sedierung-Delirmanagement-in-der-Intensivmedizin-DAS_2021-08.pdf'.lower(): {
    "Leitsatz": 3,
    "Inhaltsverzeichnis": 4,
    "A. Analgesie, Sedierung und Delirmanagement bei Erwachsenen": 5,
    "A. Analgesie, Sedierung und Delirmanagement bei Erwachsenen - Relevanz": 5,
    "A. Analgesie, Sedierung und Delirmanagement bei Erwachsenen - 1) Risikofaktoren in der Intensivmedizin": 5,
    "A. Analgesie, Sedierung und Delirmanagement bei Erwachsenen - 2) Prävention und Risikoreduktion": 8,
    "A. Analgesie, Sedierung und Delirmanagement bei Erwachsenen - 3) Prävention und Frühintervention akuter Belastungen zur Reduktion von Spätfolgen": 11,
    "A. Analgesie, Sedierung und Delirmanagement bei Erwachsenen - 4) Monitoring von Analgesie, Sedierung, Delir, Stress, Angst und Schlaf": 17,
    "A. Analgesie, Sedierung und Delirmanagement bei Erwachsenen - 5) Therapeutische Konzepte": 38,
    "A. Analgesie, Sedierung und Delirmanagement bei Erwachsenen - 5a) Nicht-pharmakologisch": 38,
    "A. Analgesie, Sedierung und Delirmanagement bei Erwachsenen - 5b) Pharmakologisch": 41,
    "A. Analgesie, Sedierung und Delirmanagement bei Erwachsenen - 6) Regionale Analgesieverfahren in der Intensivmedizin": 71,
    "A. Analgesie, Sedierung und Delirmanagement bei Erwachsenen - 7) Neuromuskuläre Blockade in der Intensivmedizin": 83,
    "A. Analgesie, Sedierung und Delirmanagement bei Erwachsenen - 8) Intra- und Interhospitaltransporte": 88,
    "B. Spezielle Patient:innengruppen": 89,
    "B. Spezielle Patient:innengruppen - 1) Schwangerschaft und Stillzeit": 89,
    "B. Spezielle Patient:innengruppen - 2) Sterbende Patient:innen": 99,
    "B. Spezielle Patient:innengruppen - 3) Brandverletzte Patient:innen": 101,
    "B. Spezielle Patient:innengruppen - 3a) Das brandverletzte Kind": 102,
    "B. Spezielle Patient:innengruppen - 4) Polytraumatisierte Patient:innen": 105,
    "B. Spezielle Patient:innengruppen - 5) Patient:innen mit erhöhtem intrakraniellen Druck": 108,
    "B. Spezielle Patient:innengruppen - 6) Kardiochirurgische Patient:innen": 125,
    "B. Spezielle Patient:innengruppen - 7) Patient:innen mit extrakorporalen Herz- und Lungenersatzverfahren": 127,
    "B. Spezielle Patient:innengruppen - 8) Patient:innen mit spezieller Lagerungstherapie": 129,
    "C. Analgesie, Sedierung und Delirmanagement bei Kindern": 130,
    "C. Analgesie, Sedierung und Delirmanagement bei Kindern - 1) Monitoring von Analgesie, Sedierung, Delir, Stress, Angst und Schlaf bei Kindern": 130,
    "C. Analgesie, Sedierung und Delirmanagement bei Kindern - 1a) Analgesie-Monitoring": 130,
    "C. Analgesie, Sedierung und Delirmanagement bei Kindern - 1b) Monitoring der Sedierung": 138,
    "C. Analgesie, Sedierung und Delirmanagement bei Kindern - 1c) Monitoring des Delirs": 141,
    "C. Analgesie, Sedierung und Delirmanagement bei Kindern - 2) Therapeutische Konzepte bei Kindern": 144,
    "C. Analgesie, Sedierung und Delirmanagement bei Kindern - 2a) Analgesie": 144,
    "C. Analgesie, Sedierung und Delirmanagement bei Kindern - 2b) nicht-pharmakologische Therapie": 151,
    "C. Analgesie, Sedierung und Delirmanagement bei Kindern - 2c) Sedierung": 153,
    "C. Analgesie, Sedierung und Delirmanagement bei Kindern - 2d) Delirtherapie": 160,
    "D. Analgesie, Sedierung und Delirmanagement bei älteren Patient:innen": 164,
    "D. Analgesie, Sedierung und Delirmanagement bei älteren Patient:innen - 1) Monitoring und Comprehensive Geriatric Assessment": 164,
    "D. Analgesie, Sedierung und Delirmanagement bei älteren Patient:innen - 2) Therapeutische Konzepte": 166,
    "E. Ökonomie, Qualitätssicherung und Implementierung der Leitlinie": 168,
    "Literaturverzeichnis": 178
}
,
        '040-012l_S2k_Diagnostik-Therapie-Kohlenmonoxidvergiftung_2021-11.pdf'.lower():
            {
                "Inhaltsverzeichnis": 2,
                "Informationen zu dieser Leitlinie": 4,
                "Informationen zu dieser Leitlinie - 2.1 Federführende Fachgesellschaft": 4,
                "Informationen zu dieser Leitlinie - 2.2 Kontakt": 4,
                "Informationen zu dieser Leitlinie - 2.3 Zitierweise": 4,
                "Informationen zu dieser Leitlinie - 2.4 Besonderer Hinweis": 4,
                "Informationen zu dieser Leitlinie - 2.5 Verantwortlichkeiten": 5,
                "Informationen zu dieser Leitlinie - 2.5.1 Beteiligte Fachgesellschaften und Organisationen": 5,
                "Informationen zu dieser Leitlinie - 2.5.2 Autoren dieser Leitlinie und Mitglieder der Leitliniengruppe": 5,
                "Informationen zu dieser Leitlinie - 2.5.3 Methodische Begleitung": 6,
                "Informationen zu dieser Leitlinie - 2.5.4 Weitere Autoren und Fachgesellschaften dieser Leitlinie und Mitglieder der Leitliniengruppe (kein Stimmrecht)": 6,
                "Informationen zu dieser Leitlinie - 2.5.5 Beteiligte Fachgesellschaften ohne aktive Mitarbeit in der Leitliniengruppe": 6,
                "Informationen zu dieser Leitlinie - 2.6 Zielsetzung": 7,
                "Informationen zu dieser Leitlinie - 2.7 Grundlagen der Methodik": 7,
                "Informationen zu dieser Leitlinie - 2.7.1 Verwendete Definitionen für Empfehlungs- und Konsensstärken": 7,
                "Informationen zu dieser Leitlinie - 2.7.2 Gültigkeitsdauer und Aktualisierungsverfahren": 8,
                "Ätiologie und Pathogenese der Kohlenmonoxidvergiftung": 9,
                "Ätiologie und Pathogenese der Kohlenmonoxidvergiftung - 3.1 Definition der Kohlenmonoxidvergiftung": 9,
                "Ätiologie und Pathogenese der Kohlenmonoxidvergiftung - 3.2 Pathophysiologie": 9,
                "Ätiologie und Pathogenese der Kohlenmonoxidvergiftung - 3.3 Epidemiologie": 10,
                "Ätiologie und Pathogenese der Kohlenmonoxidvergiftung - 3.4 Prognose": 11,
                "Prävention": 12,
                "Symptome und Diagnostik": 13,
                "Symptome und Diagnostik - 5.1 Symptome einer akuten Kohlenmonoxidvergiftung": 14,
                "Symptome und Diagnostik - 5.2 Anzeichen einer schweren Kohlenmonoxidvergiftung": 15,
                "Symptome und Diagnostik - 5.3 Diagnostische Methoden": 15,
                "Rettung": 17,
                "Rettung - 6.1 Laienhelfer": 17,
                "Rettung - 6.2 Rettungskräfte": 17,
                "Primärversorgung": 19,
                "Krankenhauseinweisung": 20,
                "Klinische Erstversorgung": 21,
                "Klinische Erstversorgung - 9.1 Versorgung von Schwangeren": 23,
                "Klinische Erstversorgung - 9.2 Versorgung von Kindern und Jugendlichen": 24,
                "Hyperbare Sauerstofftherapie (HBOT)": 27,
                "Rehabilitation / Folgeschäden": 32,
                "Qualitätssicherung": 33,
                "Qualitätssicherung - 12.1 Präklinische Kennzahlen": 33,
                "Qualitätssicherung - 12.2 Klinische Kennzahlen": 34,
                "Qualitätssicherung - 12.3 Poststationäre Kennzahlen": 34,
                "Qualitätssicherung - 12.4 Aktualisierungsplanung": 35,
                "Anhang": 36,
                "Anhang - 13.1 Vergleich von Vorgehensempfehlungen bei Exposition mit Kohlenmonoxid (Auszug)": 36,
                "Anhang - 13.2 Empfehlung der DGUV für den Einsatz von Kohlenmonoxidwarngeräten bei Feuerwehren und Hilfsorganisationen": 37,
                "Literatur": 40
            }
        ,
        '040-014l_S3_Intensivmedizin_nach_Polytrauma_2024-08.pdf'.lower():
            {
                "HERAUSGEBENDE": 5,
                "DIE WICHTIGSTEN EMPFEHLUNGEN AUF EINEN BLICK": 1,
                "GELTUNGSBEREICH UND ZWECK": 2,
                "A. ZIELSETZUNG UND FRAGESTELLUNG": 9,
                "B. VERSORGUNGSBEREICH": 9,
                "C. PATIENT*INNENZIELGRUPPE": 9,
                "D. ADRESSATEN": 9,
                "E. WEITERE DOKUMENTE ZU DIESER LEITLINIE": 9,
                "ZUSAMMENSETZUNG DER LEITLINIENGRUPPE": 11,
                "LEITLINIENKOORDINATION/ANSPRECHPARTNER": 11,
                "BETEILIGTE FACHGESELLSCHAFTEN UND ORGANISATION": 12,
                "KAPITELAUTOREN": 14,
                "VORWORT": 17,
                "1 INTERDISZIPLINÄRE UND INTERPROFESSIONELLE ZUSAMMENARBEIT UND KOMMUNIKATION": 19,
                "1.1 INTERDISZIPLINÄRE UND INTERPROFESSIONELLE ZUSAMMENARBEIT UND KOMMUNIKATION PRINZIPIEN DER ZUSAMMENARBEIT IN DER POLYTRAUMAVERSORGUNG": 19,
                "1.2 INTERDISZIPLINÄRE UND INTERPROFESSIONELLE ZUSAMMENARBEIT UND KOMMUNIKATION OPTIMIERTES SETTING FÜR ZUSAMMENARBEIT UND KOMMUNIKATION": 20,
                "1.3 INTERDISZIPLINÄRE UND INTERPROFESSIONELLE ZUSAMMENARBEIT UND KOMMUNIKATION BETEILIGE FACHDISZIPLINEN UND PROFESSIONEN IN DER INTENSIVMEDIZINISCHEN POLYTRAUMA-VERSORGUNG": 21,
                "1.4 INTERDISZIPLINÄRE UND INTERPROFESSIONELLE ZUSAMMENARBEIT UND KOMMUNIKATION NOTWENDIGE RESSOURCEN": 22,
                "1.5 INTERDISZIPLINÄRE UND INTERPROFESSIONELLE ZUSAMMENARBEIT UND KOMMUNIKATION PRAKTISCHE DURCHFÜHRUNG DER PATIENT*INNEN-ÜBERGABE NACH POLYTRAUMA": 23,
                "1.6 INTERDISZIPLINÄRE UND INTERPROFESSIONELLE ZUSAMMENARBEIT UND KOMMUNIKATION DOKUMENTATIONSSTANDARDS ZUR ERFASSUNG DER INTENSIV-MEDIZINISCHEN KOMPLEXBEHANDLUNG": 25,
                "1.7 INTERDISZIPLINÄRE UND INTERPROFESSIONELLE ZUSAMMENARBEIT UND KOMMUNIKATION PATIENT*INNEN-KOMMUNIKATION": 26,
                "1.8 INTERDISZIPLINÄRE UND INTERPROFESSIONELLE ZUSAMMENARBEIT UND KOMMUNIKATION ANGEHÖRIGEN-KOMMUNIKATION": 28,
                "2. AUFNAHME AUF DIE INTENSIVSTATION": 34,
                "2.1 AUFNAHME AUF DIE INTENSIVSTATION INDIKATIONSSTELLUNG ZUR ITS-AUFNAHME": 34,
                "2.2 AUFNAHME AUF DIE INTENSIVSTATION ANFORDERUNGSPROFIL AN AUSSTATTUNG EINER POLYTRAUMA-ITS": 37,
                "2.3 AUFNAHME AUF DIE INTENSIVSTATION MELDEKETTEN NACH ÜBERNAHME AUF DIE ITS": 39,
                "2.4 AUFNAHME AUF DIE INTENSIVSTATION UNTERSUCHUNG NACH ITS-AUFNAHME": 40,
                "2.5 AUFNAHME AUF DIE INTENSIVSTATION TELEMEDIZIN AUF DER INTENSIVSTATION": 41,
                "3. MONITORING": 45,
                "3.1 MONITORING KLINISCHES MONITORING": 47,
                "3.2 MONITORING ORGANSPEZIFISCHES, APPARATIVES MONITORING": 58,
                "3.2.1 MONITORING ZNS - INTRAKRANIELLE DRUCKMESSUNG": 58,
                "3.2.3 MONITORING HERZ-KREISLAUF": 59,
                "3.2.4 MONITORING NIERE": 60,
                "4. BILDGEBUNG IM STATIONÄREN VERLAUF": 62,
                "4.1 BILDGEBUNG IM STATIONÄREN VERLAUF EINLEITUNG": 62,
                "4.2 BILDGEBUNG IM STATIONÄREN VERLAUF BILDGEBUNGSMODALITÄTEN STATIONÄR UND IN DER RADIOLOGISCHEN ABTEILUNG": 64,
                "4.3 BILDGEBUNG IM STATIONÄREN VERLAUF INDIKATION FÜR BILDGEBUNG VON/AUF DER INTENSIVSTATION": 66,
                "4.4 BILDGEBUNG IM STATIONÄREN VERLAUF ABWÄGUNG THERAPEUTISCHER NUTZEN VS. GEFAHREN DURCH TRANSPORT": 66,
                "4.5.1 BILDGEBUNG IM STATIONÄREN VERLAUF KRANIO-ZERVIKO-SPINALE VERLETZUNGEN": 67,
                "4.5.1.1 BILDGEBUNG IM STATIONÄREN VERLAUF SCHÄDEL-HIRN-TRAUMA": 67,
                "4.5.1.2 BILDGEBUNG IM STATIONÄREN VERLAUF ZERVIKALE DISSEKTION": 67,
                "4.5.1.3 BILDGEBUNG IM STATIONÄREN VERLAUF SPINALE VERLETZUNG": 68,
                "4.5.1.4 BILDGEBUNG IM STATIONÄREN VERLAUF HIRNTOD": 68,
                "4.5.2 BILDGEBUNG IM STATIONÄREN VERLAUF THORAXVERLETZUNGEN": 68,
                "4.5.3 BILDGEBUNG IM STATIONÄREN VERLAUF EINSATZMÖGLICHKEITEN DER ELEKTRISCHEN IMPEDANZTOMOGRAPHIE (EIT)": 70,
                "4.5.4 BILDGEBUNG IM STATIONÄREN VERLAUF ABDOMINELLE VERLETZUNGEN": 71,
                "4.5.5 BILDGEBUNG IM STATIONÄREN VERLAUF EXTREMITÄTENVERLETZUNGEN": 72,
                "5. BEATMUNG": 82,
                "5.1 BEATMUNG INDIKATION ZUR INITIIERUNG DER NON-INVASIVEN BEATMUNG NACH POLYTRAUMA": 82,
                "5.2 BEATMUNG INDIKATION ZUR INITIIERUNG DER INVASIVEN BEATMUNG NACH POLYTRAUMA": 82,
                "5.3 BEATMUNG WAHL DES BEATMUNGSVERFAHRENS": 83,
                "5.4 BEATMUNG BEATMUNGSPRINZIPIEN IM ARDS NACH POLYTRAUMA": 84,
                "5.5 BEATMUNG TRACHEOTOMIE": 86,
                "5.6 BEATMUNG ENTWÖHNUNG VON DER INVASIVEN BEATMUNG": 87,
                "6. VOLUMEN- UND KREISLAUFTHERAPIE": 91,
                "6.1 VOLUMEN- UND KREISLAUFTHERAPIE DIAGNOSE DES VOLUMENMANGELS NACH POLYTRAUMA": 91,
                "6.2 VOLUMEN- UND KREISLAUFTHERAPIE WAHL DES VOLUMENERSATZES BEI POLYTRAUMAPATIENT*INNEN": 92,
                "6.3 VOLUMEN- UND KREISLAUFTHERAPIE BLUTTRANSFUSION UND TRANSFUSIONSTRIGGER": 93,
                "6.4 VOLUMEN- UND KREISLAUFTHERAPIE ZIELPARAMETER DER HERZ-KREISLAUFTHERAPIE": 94,
                "6.5 VOLUMEN- UND KREISLAUFTHERAPIE STEUERUNG DER VOLUMENTHERAPIE NACH POLYTRAUMATISIERUNG": 95,
                "7. DEFINITIVE CHIRURGISCHE VERSORGUNG": 102,
                "7.1 DEFINITIVE CHIRURGISCHE VERSORGUNG FAKTOREN, DIE DEN OP-ZEITPUNKT FÜR MAßNAHMEN NACH DER 1. OPERATIONSPHASE BEEINFLUSSEN": 102,
                "7.2 DEFINITIVE CHIRURGISCHE VERSORGUNG RELEVANTE PARAMETER ZUR ENTSCHEIDUNGSFINDUNG": 162,
                "8. ERNÄHRUNGSTHERAPIE": 165,
                "9. LAGERUNG UND PHYSIOTHERAPIE": 168,
                "9.1 LAGERUNG UND PHYSIOTHERAPIE EINLEITUNG": 168,
                "9.2 LAGERUNG UND PHYSIOTHERAPIE LAGERUNG BEI SPEZIELLEN KRANKHEITSBILDERN": 170,
                "9.2.1 LAGERUNG UND PHYSIOTHERAPIE GRUNDPRINZIPIEN DER LAGERUNG UND RUHIGSTELLUNG BEI VERLETZUNGEN DER EXTREMITÄTEN": 170,
                "9.2.2 LAGERUNG UND PHYSIOTHERAPIE LAGERUNG BEI PATIENT*INNEN MIT SCHÄDEL-HIRN-TRAUMA": 170,
                "9.2.3 LAGERUNG UND PHYSIOTHERAPIE LAGERUNG BEI THORAXTRAUMA": 171,
                "9.2.4 LAGERUNG UND PHYSIOTHERAPIE LAGERUNG BEI WIRBELSÄULENVERLETZUNG": 171,
                "9.2.5 LAGERUNG UND PHYSIOTHERAPIE LAGERUNG BEI ABDOMINELLEM TRAUMA": 171,
                "9.2.6 LAGERUNG UND PHYSIOTHERAPIE LAGERUNG BEI BECKENVERLETZUNGEN": 171,
                "9.2.7 LAGERUNG UND PHYSIOTHERAPIE BAUCHLAGERUNG": 172,
                "9.3 LAGERUNG UND PHYSIOTHERAPIE MOBILISATION UND PHYSIOTHERAPIE": 172,
                "10. MULTIORGANVERSAGEN UND ORGANERSATZTHERAPIE": 176,
                "10.1 MULTIORGANVERSAGEN UND ORGANERSATZTHERAPIE NIERENERSATZVERFAHREN": 177,
                "10.2 MULTIORGANVERSAGEN UND ORGANERSATZTHERAPIE EXTRAKORPORALE MEMBRANOXYGENIERUNG": 177,
                "11. WUNDMANAGEMENT": 185,
                "11.1 WUNDMANAGEMENT VERBANDWECHSEL UND WUNDKONTROLLE": 187,
                "11.2 WUNDMANAGEMENT OFFENE WUNDBEHANDLUNG UND WUNDAUFLAGEN": 188,
                "11.3 WUNDMANAGEMENT VAKUUMVERBÄNDE": 189,
                "11.4 WUNDMANAGEMENT THERMISCHE VERLETZUNGEN": 190,
                "11.5 WUNDMANAGEMENT WUNDVERSORGUNG BEI PATIENT*INNEN MIT ANLIEGENDEM FIXATEUR EXTERNE ODER EXTENSIONSVORRICHTUNGEN": 190,
                "11.6 WUNDMANAGEMENT PATIENT*INNENINDIVIDUELLE ASPEKTE DER WUNDHEILUNG": 191,
                "12. SEPSIS UND SEPSISMANAGEMENT": 193,
                "13. ABWENDUNG DER VITALEN BEDROHUNG": 198,
                "14. SCHMERZMANAGEMENT": 204,
                "14.1 SCHMERZMANAGEMENT GRUNDPRINZIPIEN DES SCHMERZMANAGEMENTS": 204,
                "14.2 SCHMERZMANAGEMENT SPEZIFISCHES SCHMERZMANAGEMENT NACH POLYTRAUMA": 206,
                "14.3 SCHMERZMANAGEMENT EINSATZ OPIAT-SPARENDER SCHMERZTHERAPIE": 206,
                "15. DELIR- UND SEDIERUNGSMANAGEMENT": 207,
                "15.1 DELIR- UND SEDIERUNGSMANAGEMENT DELIR": 207,
                "15.2 DELIR- UND SEDIERUNGSMANAGEMENT SEDIERUNG": 208,
                "16. FRÜHZEITIGES REHABILITATIONSORIENTIERTES ENTLASSMANAGEMENT": 213,
                "17. KAPITELÜBERGREIFENDE GENDER- UND ALTERSSPEZIFISCHE ASPEKTE": 214,
                "18. KOSTENNUTZEN": 218,
                "19. FEHLERMANAGEMENT UND VERMEIDUNG VON KOMPLIKATIONEN": 221,
                "20. RECHTLICHE ASPEKTE IN DER POLYTRAUMAVERSORGUNG": 228,
                "III. ANLAGEN": 233,
                "KOMMENTARLISTE": 234,
                "SYSTEMATIK DER LEITLINIE": 241,
                "ERLÄUTERUNG DER ABKÜRZUNGEN": 247,
                "LITERATUR": 251
            }

    }


